filetype plugin on

filetype indent on

set autoread
" Ignore case when searching
set ignorecase

" When searching try to be smart about cases 
set smartcase

" Highlight search results
set hlsearch

" enable mouse in console
set mousemodel=extend
set mouse=a
set mousehide
set mouse+=a
set ttymouse=urxvt

""" use X11 clipboard as default
set clipboard+=unnamedplus

" Open new windows on the bottom and right instead of the top and left.
set splitbelow
set splitright

"map leader key to , instead of \ and change timeout
let mapleader=","
set timeout timeoutlen=1500

"set * to search for selection
vnoremap * y/<C-R>"<CR>

" Set relative numbering of line
set number
set relativenumber

"always show 10 line befor and after cursor
set scrolloff=10

"Syntax highlight based on filetype, which is autmatically determined.
syntax enable
syntax on
" The filetype plugin needs to be reinitialized after enabling syntax.
filetype off
filetype on
filetype plugin on
filetype indent on

set background=dark
set encoding=utf8

" Turn backup off, since most stuff is in SVN, git et.c anyway...
set nobackup
set nowb
set noswapfile


" Be smart when using tabs 
set smarttab
set expandtab
set shiftwidth=4
set tabstop=4

""" Escape emulation
    imap fd <Esc>
