#!/usr/bin/env bash

### Load agnoster theme
THEME=$HOME/.cnfLnx/bash/layers/agnoster-theme.bash
if [[ -f $THEME ]]; then
    export DEFAULT_USER=`whoami`
    source $THEME
fi

### Load core features
# [completion; backward search]
CORE=$HOME/.cnfLnx/bash/layers/core.bash
if [[ -f $CORE ]]; then
    source $CORE
fi

### Load custom aliases
ALIAS=$HOME/.cnfLnx/bash/layers/alias.bash
if [[ -f $ALIAS ]]; then
    source $ALIAS
fi

### Load custom paths
CUSTOM_PATH=$HOME/.cnfLnx/bash/layers/path.bash
if [[ -f $CUSTOM_PATH ]]; then
    source $CUSTOM_PATH
fi
